# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"make_sparse_safe": "01_graph_building.ipynb",
         "distance_matrix": "01_graph_building.ipynb",
         "anisotropic_kernel": "01_graph_building.ipynb",
         "adaptive_anisotropic_kernel": "01_graph_building.ipynb",
         "diffusion_matrix": "01_graph_building.ipynb",
         "diffusion_matrix_from_points": "01_graph_building.ipynb",
         "diffusion_coordinates": "01_graph_building.ipynb",
         "diffusion_map_from_points": "01_graph_building.ipynb"}

modules = ["utils.py"]

doc_url = "https://professorwug.github.io/losscurves/"

git_url = "https://github.com/professorwug/losscurves/tree/master/"

def custom_doc_links(name): return None
