# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://professorwug.github.io/losscurves/"

git_url = "https://github.com/professorwug/losscurves/tree/master/"

def custom_doc_links(name): return None
